version: '3'

services:
  sonarqube:
    image: sonarqube:lts-community
    depends_on:
      - sonar_db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonar_db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
      SONAR_WEB_CONTEXT: "/"
      SONAR_WEB_HOST: "0.0.0.0"
      SONAR_WEB_PORT: "9000"
      SONAR_CORE_SERVERBASEURL: "https://sonarqube.orbesle.fr"
    ports:
      - "9001:9000"
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_temp:/opt/sonarqube/temp
    networks:
      - reverse-proxy-docker-traefik_routing
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=reverse-proxy-docker-traefik_routing"
      - "traefik.http.services.sonarqube.loadbalancer.server.port=9000"
      - "traefik.http.routers.sonarqube.rule=Host(`sonarqube.orbesle.fr`)"
      - "traefik.http.routers.sonarqube.tls=true"
      - "traefik.http.routers.sonarqube.tls.certresolver=letsencrypt"
      - "traefik.http.routers.sonarqube.entrypoints=websecure"
      - "traefik.http.middlewares.sonarqube-headers.headers.customResponseHeaders.X-Frame-Options=SAMEORIGIN"
      - "traefik.http.routers.sonarqube.middlewares=sonarqube-headers"
      - "traefik.http.routers.sonarqube-http.rule=Host(`sonarqube.orbesle.fr`)"
      - "traefik.http.routers.sonarqube-http.entrypoints=web"
      - "traefik.http.routers.sonarqube-http.middlewares=redirect-to-https@file"

  sonar_db:
    image: postgres:13
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    ports:
      - "5433:5432"
    volumes:
      - sonar_db:/var/lib/postgresql
      - sonar_db_data:/var/lib/postgresql/data
    networks:
      - reverse-proxy-docker-traefik_routing
    restart: always

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_temp:
  sonar_db:
  sonar_db_data:

networks:
  reverse-proxy-docker-traefik_routing:
    external: true