services:
  homarr:
    image: ghcr.io/ajnart/homarr:latest
    container_name: homarr_new # Changé pour éviter le conflit, si nécessaire
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - ./homarr/configs:/app/data/configs
      - ./homarr/icons:/app/public/icons
      - ./homarr/data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=reverse-proxy-docker-traefik_routing"
      # https
      - "traefik.http.routers.homarr.rule=Host(`home.orbesle.fr`)"
      - "traefik.http.routers.homarr.tls=true"
      - "traefik.http.routers.homarr.tls.certresolver=letsencrypt"
      - "traefik.http.routers.homarr.entrypoints=websecure"
      # http (redirect to https)
      - "traefik.http.routers.homarr-http.rule=Host(`home.orbesle.fr`)"
      - "traefik.http.routers.homarr-http.entrypoints=web"
      - "traefik.http.routers.homarr-http.middlewares=redirect-to-https@file"
    networks:
      - traefik_routing

networks:
  traefik_routing:
    external: true
    name: reverse-proxy-docker-traefik_routing
